# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Karma' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 5.0.1'
  pod 'SwiftLint', '~> 0.49.0'
  pod 'Alamofire', '~> 5.6.1'
  pod 'Moya', '~> 15.0'

end
